export const DODO_BOOTSTRAP_ARTIFACT_FILES: Readonly<{ bootstrap: string; health: string; reservation: string; resumeClaim: string; rollback: string }>;
export const DODO_BOOTSTRAP_SECRET_NAME: "DODO_PAYMENTS_WEBHOOK_KEY";
export function assertDodoBootstrapCandidateAdmission(input: Record<string, any>): Record<string, any>;
export function assertDodoSecretVersionClone(input: Record<string, any>): void;
export function assertDodoWebhookEndpointInventory(payload: unknown, endpointUrl: string): string | null;
export function inspectDodoWebhookEndpoint(input: { apiBaseUrl: string; apiKey: string; endpointUrl: string; fetcher: typeof fetch }): Promise<string | null>;
export function readDodoWebhookSigningSecret(input: { apiBaseUrl: string; apiKey: string; endpointUrl: string; fetcher: typeof fetch }): Promise<string>;
export function buildDodoBootstrapArtifact(input: Record<string, any>): Record<string, any>;
export function assertDodoBootstrapArtifact(artifact: Record<string, any>): Record<string, any>;
export function assertDodoBootstrapReleaseBinding(input: Record<string, any>): Record<string, any>;
export function buildDodoSignedHealthProbe(input: { requestId: string; secret: string; timestamp: number }): { body: string; headers: Record<string, string> };
export function assertDodoSignedHealthProbe(response: Response, payload: unknown, requestId: string): void;
export function buildDodoBootstrapHealthArtifact(input: Record<string, any>): Record<string, any>;
export function buildDodoBootstrapRollbackArtifact(input: Record<string, any>): Record<string, any>;
export function buildDodoBootstrapReservation(input: Record<string, any>): Record<string, any>;
export function assertDodoBootstrapReservation(reservation: Record<string, any>): Record<string, any>;
export function updateDodoBootstrapReservation(reservation: Record<string, any>, input: Record<string, any>): Record<string, any>;
export function readPrivateDodoArtifact(root: string, ref: string, filename: string, expectedSha256?: string): Promise<{ artifactSha256: string; evidenceRef: string; releaseId: string; value: Record<string, any> }>;
export function readCanonicalPrivateJson(root: string, ref: string, expectedRef: string, issue: string): Promise<Record<string, any>>;
export function writePrivateDodoArtifact(root: string, releaseId: string, filename: string, value: unknown, options?: { fileSystemHooks?: { beforeOpen?: (input: { path: string }) => Promise<void> | void } }): Promise<{ artifactSha256: string; evidenceRef: string }>;
export function replacePrivateDodoArtifact(root: string, releaseId: string, filename: string, value: unknown, expectedSha256: string, options?: { fileSystemHooks?: { beforeOpen?: (input: { path: string }) => Promise<void> | void; beforeReplaceCommit?: (input: { path: string; replacementPath: string }) => Promise<void> | void } }): Promise<{ artifactSha256: string; evidenceRef: string }>;
export function acquireDodoBootstrapResumeClaim(root: string, input: { fileSystemHooks?: { beforeCanonicalClaimUnlink?: (input: { path: string; stalePath: string }) => Promise<void> | void; onClaimMutationLockBlocked?: (input: { lockPath: string }) => Promise<void> | void }; now?: Date; releaseId: string; reservationId: string; reservationSha256: string }): Promise<{ artifactSha256: string; claim: Record<string, any>; evidenceRef: string }>;
export function releaseDodoBootstrapResumeClaim(root: string, input: { claim: Record<string, any>; now?: Date }): Promise<{ ownershipLost: boolean; released: boolean }>;
export function assertDodoBootstrapResumeClaimOwnership(root: string, input: { claim: Record<string, any>; now?: Date }): Promise<Record<string, any>>;
export function renewDodoBootstrapResumeClaim(root: string, input: { claim: Record<string, any>; now?: Date }): Promise<{ artifactSha256: string; claim: Record<string, any>; evidenceRef: string }>;
