const PROCESS_ENV_START = "type StringifyValues<EnvType extends Record<string, unknown>> = {";
const RUNTIME_TYPES_MARKER = "// Begin runtime types";

/** Preserve Worker bindings while avoiding a global required-key ProcessEnv augmentation. */
export function normalizeWorkerTypes(source) {
  if (typeof source !== "string" || !source.includes("interface __BaseEnv_Env") || !source.includes("interface Env extends __BaseEnv_Env")) {
    throw new Error("worker_typegen_env_missing");
  }
  const start = source.indexOf(PROCESS_ENV_START);
  if (start < 0) throw new Error("worker_typegen_process_env_block_missing");
  if (source.indexOf(PROCESS_ENV_START, start + PROCESS_ENV_START.length) >= 0) {
    throw new Error("worker_typegen_process_env_block_ambiguous");
  }
  const runtimeMarker = source.indexOf(RUNTIME_TYPES_MARKER, start);
  if (runtimeMarker < 0) throw new Error("worker_typegen_runtime_marker_missing");
  const normalized = `${source.slice(0, start)}// NodeJS.ProcessEnv is intentionally supplied by @types/node.\n\n${source.slice(runtimeMarker)}`;
  return normalized.replace(
    /^\/\/ Generated by Wrangler[^\n]*$/mu,
    "// Generated by Wrangler and normalized by scripts/worker-typegen.mjs; do not edit by hand.",
  );
}
