import { describe, expect, it } from "vitest";

import { normalizeWorkerTypes } from "../../scripts/lib/worker-typegen.mjs";

const generated = `/* eslint-disable */
// Generated by Wrangler by running \`wrangler types --env=staging\` (hash: abc)
interface __BaseEnv_Env {
  PLATFORM_DB: D1Database;
  REQUIRED_VAR: string;
}
declare namespace Cloudflare { interface Env extends __BaseEnv_Env {} }
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REQUIRED_VAR">> {}
}

// Begin runtime types
interface D1Database {}
`;

describe("Worker type generation normalization", () => {
  it("preserves Worker Env and removes only Wrangler's required ProcessEnv augmentation", () => {
    const result = normalizeWorkerTypes(generated);
    expect(result).toContain("interface __BaseEnv_Env");
    expect(result).toContain("interface Env extends __BaseEnv_Env");
    expect(result).toContain("// Begin runtime types");
    expect(result).not.toContain("StringifyValues");
    expect(result).not.toContain("interface ProcessEnv");
    expect(result).toContain("normalized by scripts/worker-typegen.mjs");
  });

  it("fails closed when Wrangler changes the generated structure", () => {
    expect(() => normalizeWorkerTypes("interface Env {}" )).toThrow("worker_typegen_env_missing");
    expect(() => normalizeWorkerTypes(generated.replace("type StringifyValues", "type ChangedShape")))
      .toThrow("worker_typegen_process_env_block_missing");
  });
});
