import { env } from "cloudflare:workers";

export type AppBindings = Omit<Env, "APP_ENV" | "CANARY_HOSTNAME" | "CLOUDFLARE_ZONE_ID" | "INTEGRATION_QUEUE" | "MEDIA" | "NOTIFICATION_QUEUE" | "PLATFORM_CACHE" | "PLATFORM_DB" | "PRIVATE_EXPORTS" | "SAAS_CNAME_TARGET" | "SESSION" | "TURNSTILE_SECRET_KEY" | "TURNSTILE_SITE_KEY"> & {
  ACTIVE_CREDENTIAL_KEY_VERSION: string;
  ACTIVE_INVENTORY_KEY_VERSION: string;
  APP_ENV: "local" | "staging" | "production";
  CANARY_HOSTNAME?: string;
  CLOUDFLARE_ZONE_ID?: string;
  CREDENTIAL_KEK_V1: string;
  CREDENTIAL_KEK_V2?: string;
  DODO_PAYMENTS_WEBHOOK_PUBLIC_ID?: string;
  EXPORT_KEK_V1?: string;
  EXPORT_KEY_VERSION?: string;
  IDENTIFIER_HMAC_SECRET: string;
  INTEGRATION_QUEUE: Queue;
  INVENTORY_KEK_V1: string;
  INVENTORY_KEK_V2?: string;
  MAGIC_LINK_GLOBAL_RATE_LIMIT: string;
  MAGIC_LINK_EMAIL_RATE_LIMIT?: string;
  MAGIC_LINK_RATE_LIMIT_WINDOW_SECONDS: string;
  MAGIC_LINK_REQUESTER_RATE_LIMIT: string;
  MAGIC_LINK_SECRET: string;
  MEDIA: R2Bucket;
  NOTIFICATION_QUEUE: Queue;
  PLATFORM_CACHE: KVNamespace;
  PLATFORM_DB: D1Database;
  PRIVATE_EXPORTS: R2Bucket;
  SAAS_CNAME_TARGET?: string;
  SESSION: KVNamespace;
  SESSION_SECRET: string;
  STOREFRONT_CART_RATE_LIMIT: string;
  STOREFRONT_CHECKOUT_RATE_LIMIT: string;
  STOREFRONT_RATE_LIMIT_WINDOW_SECONDS: string;
  STOREFRONT_TURNSTILE_THRESHOLD: string;
  TELEGRAM_WEBHOOK_MAX_CONNECTIONS: string;
  TURNSTILE_SECRET_KEY?: string;
  TURNSTILE_SITE_KEY?: string;
};

export function getBindings(): AppBindings {
  return env;
}
